[package]
name = "provesvar"
version = "0.1.0"
entrypoint = "src/provesvar.typ"
authors = ["Ståle Gjelsten <@stalegjelsten>", "Willow Carretero Chavez <@carreter>"]
license = "MIT"
repository = "https://github.com/stalegjelsten/typst-provemal"
description = "A Norwegian template for writing math homework and math quiz answers" 
keywords = ["template", "norwegian", "mathematics", "maths", "assignment"]
categories = ["layout"]
disiplines = ["education", "mathematics", "computer-science"]
compiler = "0.13.1"
excludes = ["*.pdf", "*test*", "*screenshot.png"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "imgs/thumbnail.png"

